### ISSUE TITLE
CodeSurferSplit doesn't render

### ISSUE THREAD

**Issue by nickshevr** [pomber/code-surfer#44]
I've added an export for it:
```
export { default as CodeSurfer } from "./deck-code-surfer";
export { default as components } from "./deck-components";
export { default as SurferSplit } from "./deck-code-surfer-split";
```

And used it in my `mdx`:
```
import { CodeSurfer, SurferSplit } from "mdx-deck-code-surfer"

<SurferSplit
  codeTop={simpleComponent}
  codeBottom={cleanAst}
/>
```

But it doesn't build into presentation, and it also crash it with react-dom errors:
![image](https://user-images.githubusercontent.com/16756393/49359663-df5b9700-f6e7-11e8-81a0-aa25fd58febb.png)

Any suggestions?

**Comment by nickshevr** [comment]
Ok, this module doen't required, so I copy pasted the component into my presentation folder, but get:
Error with `withSlide` HOC.

**Comment by nickshevr** [comment]
Ok, I understand, this component needs total refactor. `import`s statment is out of date.

**Comment by pomber** [comment]
Yes, sorry about that. CodeSurferSplit is not usable right now (that's why it isn't documented anywhere), it needs a rewrite.

**Comment by nickshevr** [comment]
@pomber I'll do a PR soon.

**Comment by karlhorky** [comment]
@nickshevr did you happen to get a chance to start implementation or even analysis on this one? Do you have a list of things that need to be fixed? Currently have a use case for a split layout with Code Surfer.

**Comment by karlhorky** [comment]
I would also be happy in the meantime with just a workaround so that two `CodeSurfer`s can be used side by side with the split from `mdx-deck`. At the moment, the following approach, derived from the code in the component, doesn't work seemingly because of [the `100vw` and `100vh` on the `InnerCodeSurfer` component](https://github.com/pomber/code-surfer/blob/f9a93bdf3c6c8b576a9b2ca395fd8aef2f5ef168/packages/mdx-deck-code-surfer/src/deck-code-surfer.js#L79-L80).

```jsx
<div
  style={{
    height: '100vh',
    display: 'flex',
    flexDirection: 'column',
  }}
>
  <div style={{ flex: 1, overflow: 'hidden' }} key="codeTop">
    <CodeSurfer
      code={require('!raw-loader!./example-1.html')}
      lang="markup"
    />
  </div>
  <div style={{ height: '2px', backgroundColor: '#333' }} />
  <div style={{ flex: 1, overflow: 'hidden' }} key="codeBottom">
    <CodeSurfer
      code={require('!raw-loader!./example-1.css')}
      lang="css"
    />
  </div>
</div>
```

More specifically, each `CodeSurfer` component renders container `div`s with styles that use the `100vw` and `100vh` values:

```jsx
<div
  style="
    height: 100vh;
    width: 100vw;
    ...more styles...
  "
>
  <div
    style="
      height: 100vh;
      ...more styles...
    "
  >
    <!-- further elements -->
  </div>
</div>
```

Changing these 3 values to `100%` instead of `100vw` and `100vh` makes the situation at least a bit better:

**Before:**

<img width="798" alt="screen shot 2019-03-04 at 00 08 23" src="https://user-images.githubusercontent.com/1935696/53703459-8d273080-3e12-11e9-984d-d7700d2ffc8b.png">


**After:**

<img width="666" alt="screen shot 2019-03-04 at 00 13 03" src="https://user-images.githubusercontent.com/1935696/53703460-91ebe480-3e12-11e9-9de4-7db55cb456d0.png">

---

Maybe an MVP to allow for this kind of styling would be one or more options to allow changing of the width and height (and maybe other styles) of the `InnerCodeSurfer`... I'll open a PR.

**Comment by pomber** [comment]
Fixed in v3 with `<CodeSurferColumns>`

**Comment by karlhorky** [comment]
Thanks @pomber! Will take a look when I rebuild all the presentations for v3.
